// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nodeplay.node.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.nodeplay.node.model.NodeRevision;
import org.nodeplay.node.model.NodeRevisionDataOnDemand;
import org.nodeplay.node.model.NodeRevisionIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NodeRevisionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NodeRevisionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NodeRevisionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NodeRevisionIntegrationTest: @Transactional;
    
    @Autowired
    private NodeRevisionDataOnDemand NodeRevisionIntegrationTest.dod;
    
    @Test
    public void NodeRevisionIntegrationTest.testCountNodeRevisions() {
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", dod.getRandomNodeRevision());
        long count = NodeRevision.countNodeRevisions();
        Assert.assertTrue("Counter for 'NodeRevision' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testFindNodeRevision() {
        NodeRevision obj = dod.getRandomNodeRevision();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to provide an identifier", id);
        obj = NodeRevision.findNodeRevision(id);
        Assert.assertNotNull("Find method for 'NodeRevision' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'NodeRevision' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testFindAllNodeRevisions() {
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", dod.getRandomNodeRevision());
        long count = NodeRevision.countNodeRevisions();
        Assert.assertTrue("Too expensive to perform a find all test for 'NodeRevision', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<NodeRevision> result = NodeRevision.findAllNodeRevisions();
        Assert.assertNotNull("Find all method for 'NodeRevision' illegally returned null", result);
        Assert.assertTrue("Find all method for 'NodeRevision' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testFindNodeRevisionEntries() {
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", dod.getRandomNodeRevision());
        long count = NodeRevision.countNodeRevisions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<NodeRevision> result = NodeRevision.findNodeRevisionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'NodeRevision' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'NodeRevision' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testFlush() {
        NodeRevision obj = dod.getRandomNodeRevision();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to provide an identifier", id);
        obj = NodeRevision.findNodeRevision(id);
        Assert.assertNotNull("Find method for 'NodeRevision' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNodeRevision(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'NodeRevision' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testMergeUpdate() {
        NodeRevision obj = dod.getRandomNodeRevision();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to provide an identifier", id);
        obj = NodeRevision.findNodeRevision(id);
        boolean modified =  dod.modifyNodeRevision(obj);
        Integer currentVersion = obj.getVersion();
        NodeRevision merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'NodeRevision' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", dod.getRandomNodeRevision());
        NodeRevision obj = dod.getNewTransientNodeRevision(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'NodeRevision' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'NodeRevision' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NodeRevisionIntegrationTest.testRemove() {
        NodeRevision obj = dod.getRandomNodeRevision();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'NodeRevision' failed to provide an identifier", id);
        obj = NodeRevision.findNodeRevision(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'NodeRevision' with identifier '" + id + "'", NodeRevision.findNodeRevision(id));
    }
    
}
