// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nodeplay.node.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.nodeplay.node.model.Node;
import org.nodeplay.node.model.NodeDataOnDemand;
import org.nodeplay.node.model.NodeIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect NodeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: NodeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: NodeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: NodeIntegrationTest: @Transactional;
    
    @Autowired
    private NodeDataOnDemand NodeIntegrationTest.dod;
    
    @Test
    public void NodeIntegrationTest.testCountNodes() {
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", dod.getRandomNode());
        long count = Node.countNodes();
        Assert.assertTrue("Counter for 'Node' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void NodeIntegrationTest.testFindNode() {
        Node obj = dod.getRandomNode();
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Node' failed to provide an identifier", id);
        obj = Node.findNode(id);
        Assert.assertNotNull("Find method for 'Node' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Node' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void NodeIntegrationTest.testFindAllNodes() {
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", dod.getRandomNode());
        long count = Node.countNodes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Node', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Node> result = Node.findAllNodes();
        Assert.assertNotNull("Find all method for 'Node' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Node' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void NodeIntegrationTest.testFindNodeEntries() {
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", dod.getRandomNode());
        long count = Node.countNodes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Node> result = Node.findNodeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Node' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Node' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void NodeIntegrationTest.testFlush() {
        Node obj = dod.getRandomNode();
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Node' failed to provide an identifier", id);
        obj = Node.findNode(id);
        Assert.assertNotNull("Find method for 'Node' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyNode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Node' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NodeIntegrationTest.testMergeUpdate() {
        Node obj = dod.getRandomNode();
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Node' failed to provide an identifier", id);
        obj = Node.findNode(id);
        boolean modified =  dod.modifyNode(obj);
        Integer currentVersion = obj.getVersion();
        Node merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Node' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void NodeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", dod.getRandomNode());
        Node obj = dod.getNewTransientNode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Node' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Node' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Node' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void NodeIntegrationTest.testRemove() {
        Node obj = dod.getRandomNode();
        Assert.assertNotNull("Data on demand for 'Node' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Node' failed to provide an identifier", id);
        obj = Node.findNode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Node' with identifier '" + id + "'", Node.findNode(id));
    }
    
}
