// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nodeplay.node.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.nodeplay.node.model.AppUser;
import org.nodeplay.node.model.NodeDataOnDemand;
import org.nodeplay.node.model.NodeRevision;
import org.nodeplay.node.model.NodeRevisionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NodeRevisionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NodeRevisionDataOnDemand: @Component;
    
    private Random NodeRevisionDataOnDemand.rnd = new SecureRandom();
    
    private List<NodeRevision> NodeRevisionDataOnDemand.data;
    
    @Autowired
    private NodeDataOnDemand NodeRevisionDataOnDemand.nodeDataOnDemand;
    
    public NodeRevision NodeRevisionDataOnDemand.getNewTransientNodeRevision(int index) {
        NodeRevision obj = new NodeRevision();
        setBody(obj, index);
        setCreated(obj, index);
        setTitle(obj, index);
        setUser(obj, index);
        return obj;
    }
    
    public void NodeRevisionDataOnDemand.setBody(NodeRevision obj, int index) {
        String body = "body_" + index;
        obj.setBody(body);
    }
    
    public void NodeRevisionDataOnDemand.setCreated(NodeRevision obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void NodeRevisionDataOnDemand.setTitle(NodeRevision obj, int index) {
        String title = "title_" + index;
        if (title.length() > 128) {
            title = title.substring(0, 128);
        }
        obj.setTitle(title);
    }
    
    public void NodeRevisionDataOnDemand.setUser(NodeRevision obj, int index) {
        AppUser user = null;
        obj.setUser(user);
    }
    
    public NodeRevision NodeRevisionDataOnDemand.getSpecificNodeRevision(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        NodeRevision obj = data.get(index);
        Long id = obj.getId();
        return NodeRevision.findNodeRevision(id);
    }
    
    public NodeRevision NodeRevisionDataOnDemand.getRandomNodeRevision() {
        init();
        NodeRevision obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return NodeRevision.findNodeRevision(id);
    }
    
    public boolean NodeRevisionDataOnDemand.modifyNodeRevision(NodeRevision obj) {
        return false;
    }
    
    public void NodeRevisionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = NodeRevision.findNodeRevisionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'NodeRevision' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<NodeRevision>();
        for (int i = 0; i < 10; i++) {
            NodeRevision obj = getNewTransientNodeRevision(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
