// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nodeplay.node.model;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.nodeplay.node.model.UserAuth;
import org.nodeplay.node.model.UserAuthDataOnDemand;
import org.nodeplay.node.model.UserAuthIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserAuthIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAuthIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAuthIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserAuthIntegrationTest: @Transactional;
    
    @Autowired
    private UserAuthDataOnDemand UserAuthIntegrationTest.dod;
    
    @Test
    public void UserAuthIntegrationTest.testCountUserAuths() {
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", dod.getRandomUserAuth());
        long count = UserAuth.countUserAuths();
        Assert.assertTrue("Counter for 'UserAuth' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAuthIntegrationTest.testFindUserAuth() {
        UserAuth obj = dod.getRandomUserAuth();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to provide an identifier", id);
        obj = UserAuth.findUserAuth(id);
        Assert.assertNotNull("Find method for 'UserAuth' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserAuth' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAuthIntegrationTest.testFindAllUserAuths() {
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", dod.getRandomUserAuth());
        long count = UserAuth.countUserAuths();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserAuth', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserAuth> result = UserAuth.findAllUserAuths();
        Assert.assertNotNull("Find all method for 'UserAuth' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserAuth' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAuthIntegrationTest.testFindUserAuthEntries() {
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", dod.getRandomUserAuth());
        long count = UserAuth.countUserAuths();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserAuth> result = UserAuth.findUserAuthEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserAuth' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserAuth' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAuthIntegrationTest.testFlush() {
        UserAuth obj = dod.getRandomUserAuth();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to provide an identifier", id);
        obj = UserAuth.findUserAuth(id);
        Assert.assertNotNull("Find method for 'UserAuth' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserAuth(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserAuth' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthIntegrationTest.testMergeUpdate() {
        UserAuth obj = dod.getRandomUserAuth();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to provide an identifier", id);
        obj = UserAuth.findUserAuth(id);
        boolean modified =  dod.modifyUserAuth(obj);
        Integer currentVersion = obj.getVersion();
        UserAuth merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserAuth' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", dod.getRandomUserAuth());
        UserAuth obj = dod.getNewTransientUserAuth(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserAuth' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserAuth' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAuthIntegrationTest.testRemove() {
        UserAuth obj = dod.getRandomUserAuth();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserAuth' failed to provide an identifier", id);
        obj = UserAuth.findUserAuth(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserAuth' with identifier '" + id + "'", UserAuth.findUserAuth(id));
    }
    
}
